"use client";

import { Mail, Search, Send } from "lucide-react";
import { useState } from "react";
import { SectionHeading } from "@/components/admin/adminUi";

const conversations = [["AS", "Aarav Mehta", "Can we add one more stop to the Jaipur trip?", "10:42 AM", true], ["NK", "Nisha Kapoor", "Thank you, the itinerary looks perfect.", "Yesterday", false], ["RS", "Rohan Singh", "Please share the driver details.", "Mon", false]];

export default function MessagesPage() {
  const [selected, setSelected] = useState(0);
  return <div className="mx-auto w-full max-w-[1500px] space-y-7 p-4 sm:p-6 lg:p-8"><SectionHeading eyebrow="Inbox" title="Messages" description="Stay close to every traveler and request." /><div className="grid min-h-[560px] overflow-hidden rounded-2xl border border-border bg-card shadow-soft lg:grid-cols-[320px_1fr]"><div className="border-b border-border lg:border-b-0 lg:border-r"><div className="border-b border-border p-4"><label className="flex items-center gap-2 rounded-xl border border-border bg-background px-3 py-2 text-muted-foreground"><Search size={16} /><input placeholder="Search messages" className="min-w-0 flex-1 bg-transparent text-sm text-foreground outline-none" /></label></div><div className="divide-y divide-border">{conversations.map(([initials, name, preview, time, unread], index) => <button key={name} onClick={() => setSelected(index)} className={`flex w-full gap-3 p-4 text-left transition ${selected === index ? "bg-accent" : "hover:bg-muted/50"}`}><span className="flex size-9 shrink-0 items-center justify-center rounded-xl bg-primary text-xs font-bold text-primary-foreground">{initials}</span><span className="min-w-0 flex-1"><span className="flex items-center justify-between gap-2"><span className="text-sm font-semibold text-foreground">{name}</span><span className="text-[10px] text-muted-foreground">{time}</span></span><span className="mt-1 block truncate text-xs text-muted-foreground">{preview}</span></span>{unread && <span className="mt-1 size-2 rounded-full bg-secondary" />}</button>)}</div></div><div className="flex flex-col"><div className="flex items-center gap-3 border-b border-border p-5"><span className="flex size-10 items-center justify-center rounded-xl bg-primary text-sm font-bold text-primary-foreground">{conversations[selected][0]}</span><div><p className="font-semibold text-foreground">{conversations[selected][1]}</p><p className="text-xs text-success">Online</p></div></div><div className="flex-1 space-y-4 bg-muted/20 p-5"><div className="max-w-md rounded-2xl rounded-tl-sm border border-border bg-card p-4 text-sm text-foreground">Hello, I have a question about my upcoming booking.</div><div className="ml-auto max-w-md rounded-2xl rounded-tr-sm bg-primary p-4 text-sm text-primary-foreground">Of course. I&apos;ll pull up the itinerary and help you with that right away.</div><div className="max-w-md rounded-2xl rounded-tl-sm border border-border bg-card p-4 text-sm text-foreground">{conversations[selected][2]}</div></div><div className="border-t border-border p-4"><div className="flex items-center gap-2 rounded-xl border border-border bg-background p-2"><input placeholder="Write a reply..." className="min-w-0 flex-1 bg-transparent px-2 text-sm text-foreground outline-none" /><button aria-label="Send message" className="rounded-lg bg-primary p-2 text-primary-foreground"><Send size={16} /></button></div></div></div></div></div>;
}
