"use client";

import { MapPin, MoreHorizontal, Plus, Route } from "lucide-react";
import { SectionHeading, StatusBadge } from "@/components/admin/adminUi";

const routes = [["Delhi", "Jaipur", "268 km", "5h 30m", "Toyota Innova", "Active"], ["Amritsar", "Manali", "400 km", "10h 15m", "Tempo Traveller", "Active"], ["Chandigarh", "Shimla", "115 km", "4h 20m", "Maruti Suzuki", "Active"], ["Delhi", "Agra", "233 km", "4h 10m", "Toyota Crysta", "Inactive"]];

export default function RoutesPage() {
  return <div className="mx-auto w-full max-w-[1500px] space-y-7 p-4 sm:p-6 lg:p-8"><SectionHeading eyebrow="Operations" title="Route management" description="Build reliable connections between your most requested destinations." action={<button className="inline-flex h-10 items-center gap-2 rounded-xl bg-primary px-4 text-sm font-semibold text-primary-foreground"><Plus size={16} /> Add route</button>} /><div className="overflow-x-auto rounded-2xl border border-border bg-card shadow-soft"><table className="min-w-[850px] w-full text-left text-sm"><thead className="border-b border-border bg-muted/50 text-xs uppercase tracking-wide text-muted-foreground"><tr>{["Route", "Distance", "Travel time", "Assigned vehicle", "Status", ""].map((head) => <th key={head} className="px-5 py-4 font-semibold">{head}</th>)}</tr></thead><tbody className="divide-y divide-border">{routes.map(([from, to, distance, time, vehicle, status]) => <tr key={`${from}-${to}`} className="hover:bg-muted/40"><td className="px-5 py-5"><div className="flex items-center gap-3"><span className="rounded-lg bg-accent p-2 text-primary"><Route size={16} /></span><div><p className="font-semibold text-foreground">{from} <span className="mx-1 text-muted-foreground">to</span> {to}</p><p className="mt-1 flex items-center gap-1 text-xs text-muted-foreground"><MapPin size={12} /> North India corridor</p></div></div></td><td className="px-5 py-5 text-muted-foreground">{distance}</td><td className="px-5 py-5 text-muted-foreground">{time}</td><td className="px-5 py-5 text-foreground">{vehicle}</td><td className="px-5 py-5"><StatusBadge status={status} /></td><td className="px-5 py-5 text-muted-foreground"><MoreHorizontal size={18} /></td></tr>)}</tbody></table></div></div>;
}
