"use client";

import { Bell, LockKeyhole, Save, ShieldCheck, UserRound } from "lucide-react";
import { SectionHeading } from "@/components/admin/adminUi";
import useAdminAuth from "@/contrext/useAdminAuth";

const settings = [[UserRound, "Admin profile", "Update your name and contact details."], [LockKeyhole, "Password & security", "Manage password and sign-in protection."], [Bell, "Notifications", "Choose which operational alerts you receive."], [ShieldCheck, "System settings", "Configure booking and platform preferences."]];

export default function SettingsPage() {
  const { admin } = useAdminAuth();
  return <div className="mx-auto w-full max-w-[1100px] space-y-7 p-4 sm:p-6 lg:p-8"><SectionHeading eyebrow="Workspace" title="Settings" description="Keep your account and operations preferences current." /><div className="grid gap-5 lg:grid-cols-[0.8fr_1.2fr]"><aside className="space-y-2">{settings.map(([Icon, title, description], index) => <button key={title} className={`flex w-full gap-3 rounded-xl p-4 text-left transition ${index === 0 ? "bg-primary text-primary-foreground shadow-soft" : "border border-border bg-card text-foreground hover:bg-muted"}`}><Icon size={18} className="mt-0.5 shrink-0" /><span><span className="block text-sm font-semibold">{title}</span><span className={`mt-1 block text-xs ${index === 0 ? "text-primary-foreground/70" : "text-muted-foreground"}`}>{description}</span></span></button>)}</aside><section className="rounded-2xl border border-border bg-card p-5 shadow-soft sm:p-7"><div className="flex items-center gap-3 border-b border-border pb-5"><span className="flex size-11 items-center justify-center rounded-xl bg-accent text-primary"><UserRound size={20} /></span><div><h2 className="font-semibold text-foreground">Admin profile</h2><p className="mt-1 text-sm text-muted-foreground">Your administrator identity</p></div></div><div className="mt-6 grid gap-5 sm:grid-cols-2"><label className="text-sm font-medium text-foreground">Full name<input defaultValue={admin?.name || ""} className="mt-2 h-11 w-full rounded-xl border border-input bg-background px-3 text-sm outline-none focus:ring-2 focus:ring-ring/30" /></label><label className="text-sm font-medium text-foreground">Email address<input defaultValue={admin?.email || ""} className="mt-2 h-11 w-full rounded-xl border border-input bg-background px-3 text-sm outline-none focus:ring-2 focus:ring-ring/30" /></label><label className="text-sm font-medium text-foreground sm:col-span-2">Phone number<input placeholder="Add a business phone number" className="mt-2 h-11 w-full rounded-xl border border-input bg-background px-3 text-sm outline-none focus:ring-2 focus:ring-ring/30" /></label></div><div className="mt-7 flex justify-end"><button className="inline-flex h-10 items-center gap-2 rounded-xl bg-primary px-4 text-sm font-semibold text-primary-foreground"><Save size={16} /> Save changes</button></div></section></div></div>;
}
